version: '3'

# The two bookstack docker providers are linuxserver and solidnerd.
# They use the same environment variables, except that solidnerd uses
# DB_PASSWORD while linuxserver uses DB_PASS

services:
  bookstack:
    image: '${DOCKER_PROVIDER-solidnerd}/bookstack'

    volumes:
      - database_config:/config
      - bookstack_image_uploads:/var/www/bookstack/public/uploads/images
      - bookstack_attachment_uploads:/var/www/bookstack/storage/uploads/files

    ports:
      - '${BOOKSTACK_PORT:-80}:80'

    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Amsterdam

      DB_HOST: database
      DB_DATABASE: wiki
      DB_USER: wiki
      DB_PASSWORD: '${DB_USER_PASSWORD:?DB_USER_PASSWORD must be set}'
      DB_PASS: '${DB_USER_PASSWORD:?DB_USER_PASSWORD must be set}'

      VIRTUAL_HOST: '${HOST_URL:?HOST_URL must be set}:${BOOKSTACK_PORT:-80}:80'
      LETSENCRYPT_HOST: '${HOST_URL:?HOST_URL must be set}'
      LETSENCRYPT_EMAIL: '${LETSENCRYPT_EMAIL:?LETSENCRYPT_EMAIL must be set}'

    depends_on:
      - database

    restart: unless-stopped

volumes:
  bookstack_attachment_uploads:
  bookstack_image_uploads:
