version: '3'

services:
  mariadb:
    container_name: mariadb
    image: linuxserver/mariadb

    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Amsterdam

      MYSQL_DATABASE: bookstackapp
      MYSQL_USER: bookstack
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD:?DB_ROOT_PASSWORD must be set}'
      MYSQL_PASSWORD: '${DB_USER_PASSWORD:?DB_USER_PASSWORD must be set}'

    volumes:
      - config:/config

    restart: unless-stopped

    # The two bookstack dockers are linuxserver and solidnerd.
    # They use the same environment variables, except that solidnerd uses
    # DB_PASSWORD while linuxserver uses DB_PASS

  bookstack:
    container_name: bookstack
    image: '${DOCKER_PROVIDER-solidnerd}/bookstack'

    depends_on:
      - mariadb

    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Amsterdam

      DB_HOST: mariadb
      DB_DATABASE: bookstackapp
      DB_USER: bookstack
      DB_PASSWORD: '${DB_USER_PASSWORD:?DB_USER_PASSWORD must be set}'
      DB_PASS: '${DB_USER_PASSWORD:?DB_USER_PASSWORD must be set}'

    volumes:
      - config:/config
      - image_uploads:/var/www/bookstack/public/uploads/images
      - attachment_uploads:/var/www/bookstack/storage/uploads/files

    ports:
      - 80:80

    restart: unless-stopped

volumes:
  config:
  image_uploads:
  attachment_uploads:
