version: '3.7'

services:
  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    ports:
      - '443:443'

    volumes:
      - config:/config

    environment:
      URL: '${HOST_URL:?HOST_URL must be set}'
      URL: '${LETSENCRYPT_EMAIL:?LETSENCRYPT_EMAIL must be set}'
      SUBDOMAINS: www,
      VALIDATION: http
      TZ: Europe/Amsterdam
      PUID: 1000
      PGID: 1000

    cap_add:
       - NET_ADMIN
