version: '3.2'

services:
  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    ports:
      - 443:443

    volumes:
      - config:/config

    environment:
      EMAIL: tom@swirly.com
      URL: xr-bookstack.duckdns.org
      SUBDOMAINS: www,
      VALIDATION: http
      TZ: Europe/Amsterdam
      PUID: 1000
      PGID: 1000

    cap_add:
       - NET_ADMIN
