version: '3.2'

services:
  postgres:
    container_name: postgres
    image: postgres:11-alpine

    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: '${DB_USER_PASSWORD:?DB_USER_PASSWORD must be set}'
      POSTGRES_USER: wikijs

    restart: unless-stopped

    volumes:
      - db_data:/var/lib/postgresql/data

    logging:
      driver: 'none'

  wiki:
    container_name: wiki
    image: requarks/wiki:2

    environment:
      DB_TYPE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: '${DB_USER_PASSWORD:?DB_USER_PASSWORD must be set}'
      DB_NAME: wiki
      USE_HTTPS: 1
      LETSENCRYPT_DOMAIN: '${HOST_URL:?HOST_URL must be set}'
      LETSENCRYPT_EMAIL: '${LETSENCRYPT_EMAIL:?LETSENCRYPT_EMAIL must be set}'

    restart: unless-stopped

    ports:
      - '80:3000'

    depends_on:
      - postgres

volumes:
  db_data:
