version: '3'

services:
  setup:
    image: ubuntu:latest
    depends_on:
      - wiki

  wiki:
    image: timlegge/docker-foswiki
    container_name: wiki

    ports:
      - '${FOSWIKI_PORT:-80}:80'

    volumes:
      - "./wiki-files:/var/www/foswiki"
