version: '3'

services:
  setup:
    image: ubuntu:latest
    depends_on:
      - foswiki

  foswiki:
    image: timlegge/docker-foswiki
    container_name: foswiki

    ports:
      - '${FOSWIKI_PORT:-80}:80'

    volumes:
      - files:/var/www/foswiki

volumes:
  files:
