version: '3'

services:
  setup:
    image: alpine:latest
    depends_on:
      - wiki

  wiki:
    image: timlegge/docker-foswiki
    container_name: wiki

    ports:
      - '${FOSWIKI_PORT:-80}:80'

    volumes:
      - files:/var/www/foswiki

volumes:
  files:
