version: "3"

services:
  mariadb:
    container_name: mariadb
    image: linuxserver/mariadb

    environment:
      PUID: 1000
      PGID: 1000
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
      TZ: Europe/Amsterdam
      MYSQL_DATABASE: bookstackapp
      MYSQL_USER: bookstack
      MYSQL_PASSWORD: '${DB_USER_PASSWORD}'

    volumes:
      - config:/config

    restart: unless-stopped

  bookstack:
    container_name: bookstack
    image: '${DOCKER_PROVIDER-solidnerd}/bookstack'
    # The two providers are linuxserver and solidnerd

    environment:
      PUID: 1000
      PGID: 1000
      DB_HOST: mariadb
      DB_USER: bookstack
      DB_PASSWORD: '${DB_USER_PASSWORD}'
      DB_PASS: '${DB_USER_PASSWORD}'
      DB_DATABASE: bookstackapp

    volumes:
      - config:/config
      - image-uploads:/var/www/bookstack/public/uploads/images
      - attachment-uploads:/var/www/bookstack/storage/uploads/files

    ports:
      - 80:80

    restart: unless-stopped

    depends_on:
      - mariadb

volumes:
  config:
  image-uploads:
  attachment-uploads:
