version: "3"

services:
  mariadb:
    image: linuxserver/mariadb
    container_name: mariadb
    environment:
      PUID: 1000
      PGID: 1000
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
      TZ: Europe/Amsterdam
      MYSQL_DATABASE: bookstackapp
      MYSQL_USER: bookstack
      MYSQL_PASSWORD: '${DB_USER_PASSWORD}'
    volumes:
      - /code/wik/bookstack/config:/config
    restart: unless-stopped

  bookstack:
    image: linuxserver/bookstack
    container_name: bookstack
    environment:
      PUID: 1000
      PGID: 1000
      DB_HOST: mariadb
      DB_USER: bookstack
      DB_PASS: '${DB_USER_PASSWORD}'
      DB_DATABASE: bookstackapp
    volumes:
      - /code/wik/bookstack/config:/config
    ports:
      - 80:80
    restart: unless-stopped
    depends_on:
      - mariadb

  # letsencrypt:
  #   image: linuxserver/letsencrypt
  #   container_name: letsencrypt
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Europe/Amsterdam
  #     - URL=xr.swirly.com
  #     - SUBDOMAINS=www,
  #     - VALIDATION=http
  #   volumes:
  #     - /code/wik/bookstack/config:/config
  #   ports:
  #     - 443:443
  #   restart: unless-stopped
  #   cap_add:
  #     - NET_ADMIN
