version: '3'

services:
  dokuwiki:
    # image: linuxserver/dokuwiki
    image: bitnami/dokuwiki
    container_name: dokuwiki
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - APP_URL=/dokuwiki #optional

    volumes:
      - docuwiki_config:/config

    ports:
      - '${DOCUWIKI_PORT:-80}:80'
      # - 443:443 #optional
    restart: unless-stopped

volumes:
  docuwiki_config:
