version: '3'

services:
  mariadb_5:
    container_name: mariadb_5
    image: linuxserver/mariadb

    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Amsterdam
      MYSQL_DATABASE: bookstackapp
      MYSQL_USER: bookstack
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_PASSWORD: pass

    volumes:
      - config:/config

    restart: unless-stopped

  bookstack_5:
    container_name: bookstack_5
    image: '${DOCKER_PROVIDER-solidnerd}/bookstack'
    # The two providers are linuxserver and solidnerd

    environment:
      PUID: 1000
      PGID: 1000
      DB_HOST: mariadb
      DB_DATABASE: bookstackapp
      DB_USER: bookstack
      DB_PASSWORD: pass
      DB_PASS: pass

    volumes:
      - config:/config
      - image_uploads:/var/www/bookstack/public/uploads/images
      - attachment_uploads:/var/www/bookstack/storage/uploads/files

    ports:
      - 80:80

    restart: unless-stopped

    depends_on:
      - mariadb_5

volumes:
  config:
  image_uploads:
  attachment_uploads:
