version: "3"

services:
  bookstack_db:
    image: linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - 'MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}'
      - TZ=Europe/Amsterdam
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - 'MYSQL_PASSWORD=${MYSQL_PASSWORD}'
    volumes:
      - /code/wik/docker/config/bookstack_db:/config
    restart: unless-stopped

  bookstack:
    image: linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - DB_HOST=bookstack_db
      - DB_USER=bookstack
      - 'DB_PASS=${MYSQL_PASSWORD}'
      - DB_DATABASE=bookstackapp
    volumes:
      - /code/wik/docker/config/bookstack:/config
    ports:
      - 8080:80
    restart: unless-stopped
    depends_on:
      - bookstack_db
