version: "3"

services:
  bookstack_db:
    image: linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=root-password
      - TZ=Europe/Amsterdam
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=user-password
    volumes:
      - /code/wik/docker:/config
    restart: unless-stopped

  bookstack:
    image: linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - DB_HOST=bookstack_db
      - DB_USER=bookstack
      - DB_PASS=user-password
      - DB_DATABASE=bookstackapp
    volumes:
      - /code/wik/docker:/config
    ports:
      - 6875:80
    restart: unless-stopped
    depends_on:
      - bookstack_db
