version: '3'

services:
  vem_database:
    image: 'mariadb:10.4.4'

    environment:
      MYSQL_USER: vem
      MYSQL_DATABASE: vem
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_PASSWORD: '${DB_USER_PASSWORD:?DB_USER_PASSWORD must be set}'

    volumes:
      - 'vem_database_data:/var/lib/mysql'

  vem:
    image: 'tomswirly/mediawiki-parsoid:v0.1'
    ports:
      - '${MEDIAWIKI_PORT:-80}:80'

    volumes:
      - 'vem_mediawiki:/var/www/html'
      - 'vem_parsoid:/usr/lib/parsoid'

    depends_on:
      - vem_database

volumes:
  vem_mediawiki:

  vem_database_data:
    # driver_opts:
    #   type: 'none'
    #   o: 'bind'
    #   device: '/var/www/mediawiki_data'

  vem_parsoid:
    # driver_opts:
    #   type: 'none'
    #   o: 'bind'
    #   device: '/var/www/parsoid_data'
