version: "3"

services:
  postgres:
    container_name: postgres
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: '${DB_USER_PASSWORD:?DB_USER_PASSWORD must be set}'
      POSTGRES_USER: wikijs
    # logging:
    #  driver: "none"
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data

  wiki:
    container_name: wiki
    image: requarks/wiki:2
    depends_on:
      - postgres
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: '${DB_USER_PASSWORD:?DB_USER_PASSWORD must be set}'
      DB_NAME: wiki
      USE_HTTPS: 1
      LETSENCRYPT_DOMAIN: xr.swirly.com
      LETSENCRYPT_EMAIL: tom@swirly.com

    restart: unless-stopped
    ports:
      - "80:3000"

volumes:
  db-data:
